name: Deploy Frontends

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy Both Frontends
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend1
        working-directory: ./frontend1
        run: npm run build

      - name: Build Frontend2
        working-directory: ./frontend2
        run: npm run build

      - name: Deploy Frontend1
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: your-cloudflare-project-1
          directory: ./frontend1/.next

      - name: Deploy Frontend2
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: your-cloudflare-project-2
          directory: ./frontend2/.next
